### ISSUE TITLE
"The symbol "hotjar" has already been declared" after update to 6.0.0

### ISSUE THREAD

**Issue by dominikboniecki** [abdalla/react-hotjar#57]
After upgrade to 6.0.0, this error occurs:
```Error: Build failed with 1 error:
node_modules/react-hotjar/index.js:11:13: ERROR: The symbol "hotjar" has already been declared
    at failureErrorWithLog (/Users/dominikboniecki/CodiblyProjects/backoffice/node_modules/esbuild/lib/main.js:1636:15)
    at /Users/dominikboniecki/CodiblyProjects/backoffice/node_modules/esbuild/lib/main.js:1048:25
    at runOnEndCallbacks (/Users/dominikboniecki/CodiblyProjects/backoffice/node_modules/esbuild/lib/main.js:1471:45)
    at buildResponseToResult (/Users/dominikboniecki/CodiblyProjects/backoffice/node_modules/esbuild/lib/main.js:1046:7)
    at /Users/dominikboniecki/CodiblyProjects/backoffice/node_modules/esbuild/lib/main.js:1058:9
    at new Promise (<anonymous>)
    at requestCallbacks.on-end (/Users/dominikboniecki/CodiblyProjects/backoffice/node_modules/esbuild/lib/main.js:1057:54)
    at handleRequest (/Users/dominikboniecki/CodiblyProjects/backoffice/node_modules/esbuild/lib/main.js:723:19)
    at handleIncomingPacket (/Users/dominikboniecki/CodiblyProjects/backoffice/node_modules/esbuild/lib/main.js:745:7)
    at Socket.readFromStdout (/Users/dominikboniecki/CodiblyProjects/backoffice/node_modules/esbuild/lib/main.js:673:7) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: {
        column: 13,
        file: 'node_modules/react-hotjar/index.js',
        length: 6,
        line: 11,
        lineText: 'export const hotjar = {',
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: {
            column: 7,
            file: 'node_modules/react-hotjar/index.js',
            length: 6,
            line: 1,
            lineText: "import hotjar from './src/react-hotjar';",
            namespace: '',
            suggestion: ''
          },
          text: 'The symbol "hotjar" was originally declared here:'
        }
      ],
      pluginName: '',
      text: 'The symbol "hotjar" has already been declared'
    }
  ],
  warnings: []
}```

**Comment by abdalla** [comment]
V 6.1.0 has been released, please test this one!

**Comment by dominikboniecki** [comment]
It seems like it works, thank you!
